### ISSUE TITLE
rttest_plot: installed without execute permissions

### ISSUE THREAD

**Issue by jack-oquin** [ros2/rttest#10] opened 2015-10-11 15:31 UTC
On Ubuntu Trusty installed using alpha1 binaries, the rtt_plot script has mode 0644.

**Comment by jacquelinekay** [comment] 2015-10-12 17:12
Thanks for catching this. It looks like the file in the git repo was committed as an executable, so the problem is probably in our packaging process.

**Comment by jack-oquin** [comment] 2015-10-12 20:53
For anyone else hitting this, the work-around is simple: just run ``chmod +x`` on the script.

**Closed** 2015-10-29 23:01 UTC
Labels: in review
